apiVersion: v1
kind: PersistentVolume
metadata:
  name: bm2c-postgres-intance1-pv
  namespace: postgres
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /opt/nfs/postgres/instance1
    server: 192.168.1.122
  persistentVolumeReclaimPolicy: Retain
  storageClassName: bm2c-postgres-sc
  volumeMode: Filesystem
