apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  image: quay.io/keycloak/keycloak:20.0.2
  instances: 1
  db:
    vendor: postgres
    host: postgres-cluster.postgres.svr.cluster.local
    database: keycloakdb
    port: 5432
    schema: keycloak
    usernameSecret:
      name: bm2c-db-sct
      key: username
    passwordSecret:
      name: bm2c-db-sct
      key: password
    poolInitialSize: 1
    poolMinSize: 1
    poolMaxSize: 3
  http:
    tlsSecret: bm2c-tls-sct
  hostname:
    hostname: bm2ckeycloak.krugercorp.com